language: java
jdk:
- oraclejdk8
install:
- mvn dependency:go-offline
script:
- mvn clean install
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonar.l3miage.fr -Dsonar.login=${SONAR_TOKEN}
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
