language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "cerclescribmiage" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'


