language: java
addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
  
before_install:
  - chmod +x mvnw
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'






