language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
install:
- mvn dependency:go-offline
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonar.l3miage.fr -Dsonar.login=${SONAR_TOKEN} -Dsonar.login=admin -Dsonar.password=admin
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
