language: java
addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - -Dsonar.host.url=https://sonar.l3miage.fr
  - -Dsonar.login=$SONAR_TOKEN
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'






